---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minetest-data
  namespace: minetest
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/minetest
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - compute-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minetest-data
  namespace: minetest
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
