---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minetest
  name: minetest
  namespace: minetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minetest
  template:
    metadata:
      labels:
        app: minetest
    spec:
      nodeSelector:
        kubernetes.io/hostname: compute-2
      containers:
        - image: registry.gitlab.com/minetest/minetest/server:master
          #command: ["sh", "-c"]
          #args: ["sleep 100000"]
          name: minetest
          ports:
            - containerPort: 30000
              protocol: UDP
          volumeMounts:
            - mountPath: /var/lib/minetest
              name: minetest-data
            - mountPath: /etc/minetest
              name: config
      restartPolicy: Always
      volumes:
        - name: minetest-data
          persistentVolumeClaim:
            claimName: minetest-data
        - configMap:
            defaultMode: 420
            name: minetest
          name: config
