---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minetest
  name: minetest
  namespace: minetest
spec:
  ports:
    - name: minetest
      port: 31000
      targetPort: 30000
      nodePort: 30000
      protocol: UDP
  selector:
    app: minetest
  type: NodePort
